modules:
  http_kong:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200]
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: true 