cluster.name: "haptitalk-elasticsearch"
node.name: "haptitalk-es-node"
network.host: 0.0.0.0

# 시스템 설정
bootstrap.memory_lock: true
discovery.type: single-node
cluster.routing.allocation.disk.threshold_enabled: false

# 보안 설정
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

# 색인 설정
action.auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*

# 성능 설정
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# 로그 설정
path.logs: /usr/share/elasticsearch/logs
path.data: /usr/share/elasticsearch/data

# 메모리 설정
indices.fielddata.cache.size: 30%
indices.memory.index_buffer_size: 30%

# 클러스터 회복성 설정
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 1

# 스냅샷 설정
path.repo: ["/usr/share/elasticsearch/snapshots"] 