apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://haptitalk-elasticsearch:9200
    database: "logs-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.14.0
      interval: Daily
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
    isDefault: false
    editable: true 