apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://haptitalk-jaeger:16686
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: "Elasticsearch"
        tags: ["service"]
        mappedTags: [{ key: "service.name", value: "service" }]
        mapTagNamesEnabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: ""
    isDefault: false
    editable: true 