_format_version: "2.1"
_transform: true

# 사용할 플러그인 목록 정의
plugins:
- name: cors
  config:
    origins:
    - "*"
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
    headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    max_age: 3600

# 서비스 정의 
services:
  # 인증 서비스 
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
    plugins:
      - name: cors
      
  # 인증 서비스 Health 전용 서비스
  - name: auth-service-health
    url: http://auth-service:3000/health
    routes:
      - name: auth-health-route
        paths:
          - /api/health/auth
    plugins:
      - name: cors

  # 실시간 서비스
  - name: realtime-service
    url: http://realtime-service:3001
    routes:
      - name: realtime-routes
        paths:
          - /api/v1/realtime
        strip_path: false
    plugins:
      - name: cors
  
  # 실시간 서비스 Health 전용 서비스  
  - name: realtime-service-health
    url: http://realtime-service:3001/health
    routes:
      - name: realtime-health-route
        paths:
          - /api/health/realtime
    plugins:
      - name: cors
      
  # 세션 서비스 (추가)
  - name: session-service
    url: http://session-service:3002
    routes:
      - name: session-routes
        paths:
          - /api/v1/sessions
        strip_path: false
    plugins:
      - name: cors
  
  # 세션 서비스 Health 전용 서비스
  - name: session-service-health
    url: http://session-service:3002/health
    routes:
      - name: session-health-route
        paths:
          - /api/health/sessions
    plugins:
      - name: cors

  # 피드백 서비스
  - name: feedback-service
    url: http://feedback-service:3003
    routes:
      - name: feedback-routes
        paths:
          - /api/v1/feedback
        strip_path: false
    plugins:
      - name: cors
  
  # 피드백 서비스 Health 전용 서비스
  - name: feedback-service-health
    url: http://feedback-service:3003/health
    routes:
      - name: feedback-health-route
        paths:
          - /api/health/feedback
    plugins:
      - name: cors

  # 사용자 서비스
  - name: user-service
    url: http://user-service:3004
    routes:
      - name: user-routes
        paths:
          - /api/v1/users
        strip_path: false
    plugins:
      - name: cors
  
  # 사용자 서비스 Health 전용 서비스
  - name: user-service-health
    url: http://user-service:3004/health
    routes:
      - name: user-health-route
        paths:
          - /api/health/users
    plugins:
      - name: cors

  # 리포트 서비스
  - name: report-service
    url: http://report-service:3005
    routes:
      - name: report-routes
        paths:
          - /api/v1/reports
        strip_path: false
    plugins:
      - name: cors
  
  # 리포트 서비스 Health 전용 서비스
  - name: report-service-health
    url: http://report-service:3005/health
    routes:
      - name: report-health-route
        paths:
          - /api/health/reports
    plugins:
      - name: cors