_format_version: "2.1"
_transform: true

# 사용할 플러그인 목록 정의
plugins:
- name: cors
  config:
    origins:
    - "*"
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
    headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    max_age: 3600

# 서비스 정의 
services:
  # 인증 서비스 
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
    plugins:
      - name: cors

  # 실시간 서비스
  - name: realtime-service
    url: http://realtime-service:3001
    routes:
      - name: realtime-routes
        paths:
          - /api/v1/realtime
        strip_path: false
    plugins:
      - name: cors