_format_version: "2.1"
_transform: true

# 사용할 플러그인 목록 정의
plugins:
# CORS 설정
- name: cors
  config:
    origins:
    - "*"
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
    headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    max_age: 3600

# 속도 제한 설정 (전역)
- name: rate-limiting
  config:
    second: null
    minute: 60
    hour: 1000
    day: 10000
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_timeout: 2000

# 요청 크기 제한
- name: request-size-limiting
  config:
    allowed_payload_size: 10

# 보안 헤더 설정
- name: response-transformer
  config:
    add:
      headers:
      - "X-Content-Type-Options:nosniff"
      - "X-XSS-Protection:1; mode=block"
      - "Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'"
      - "X-Frame-Options:SAMEORIGIN"
      - "Strict-Transport-Security:max-age=31536000; includeSubDomains"

# 서비스 정의 
services:
  # 인증 서비스 
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
      - name: devices-routes
        paths:
          - /api/v1/devices
        strip_path: false
      - name: token-status-route
        paths:
          - /token/status
        strip_path: false
      - name: token-refresh-route
        paths:
          - /token/proactive-refresh
        strip_path: false
    plugins:
      - name: cors
      # 인증 API에 대한 속도 제한(더 엄격하게 설정)
      - name: rate-limiting
        config:
          second: 5
          minute: 30
          hour: 200
          day: 1000
          policy: local
          fault_tolerant: true
      # IP 제한 (실제 운영 환경에서는 허용된 IP만 설정)
      - name: ip-restriction
        config:
          allow: 
            - 0.0.0.0/0  # 모든 IP 허용 (실제 운영 환경에서는 허용 IP 설정)
      
  # 인증 서비스 Health 전용 서비스
  - name: auth-service-health
    url: http://auth-service:3000/health
    routes:
      - name: auth-health-route
        paths:
          - /api/health/auth
    plugins:
      - name: cors
      # 헬스 체크에 대한 속도 제한 (더 관대하게 설정)
      - name: rate-limiting
        config:
          second: 10
          minute: 60
          hour: 300
          policy: local
          fault_tolerant: true

  # 실시간 서비스
  - name: realtime-service
    url: http://realtime-service:3001
    routes:
      - name: realtime-routes
        paths:
          - /api/v1/realtime
        strip_path: false
    plugins:
      - name: cors
      # JWT 인증 적용
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
            - exp
          key_claim_name: kid
          maximum_expiration: 86400  # 24시간
      # 속도 제한 설정
      - name: rate-limiting
        config:
          second: 10
          minute: 60
          hour: 600
          day: 6000
          policy: local
          fault_tolerant: true
  
  # 실시간 서비스 Health 전용 서비스  
  - name: realtime-service-health
    url: http://realtime-service:3001/health
    routes:
      - name: realtime-health-route
        paths:
          - /api/health/realtime
    plugins:
      - name: cors
      
  # 세션 서비스 (추가)
  - name: session-service
    url: http://session-service:3002
    routes:
      - name: session-routes
        paths:
          - /api/v1/sessions
        strip_path: false
    plugins:
      - name: cors
      # JWT 인증 적용
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
            - exp
          key_claim_name: kid
          maximum_expiration: 86400  # 24시간
      # 속도 제한 설정
      - name: rate-limiting
        config:
          second: 5
          minute: 30
          hour: 300
          day: 3000
          policy: local
          fault_tolerant: true
  
  # 세션 서비스 Health 전용 서비스
  - name: session-service-health
    url: http://session-service:3002/health
    routes:
      - name: session-health-route
        paths:
          - /api/health/sessions
    plugins:
      - name: cors

  # 피드백 서비스
  - name: feedback-service
    url: http://feedback-service:3003
    routes:
      - name: feedback-routes
        paths:
          - /api/v1/feedback
        strip_path: false
    plugins:
      - name: cors
      # JWT 인증 적용
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
            - exp
          key_claim_name: kid
          maximum_expiration: 86400  # 24시간
      # 속도 제한 설정
      - name: rate-limiting
        config:
          second: 5
          minute: 30
          hour: 300
          day: 3000
          policy: local
          fault_tolerant: true
  
  # 피드백 서비스 Health 전용 서비스
  - name: feedback-service-health
    url: http://feedback-service:3003/health
    routes:
      - name: feedback-health-route
        paths:
          - /api/health/feedback
    plugins:
      - name: cors

  # 사용자 서비스
  - name: user-service
    url: http://user-service:3004
    routes:
      - name: user-routes
        paths:
          - /api/v1/users
        strip_path: false
    plugins:
      - name: cors
      # JWT 인증 적용
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
            - exp
          key_claim_name: kid
          maximum_expiration: 86400  # 24시간
      # 속도 제한 설정
      - name: rate-limiting
        config:
          second: 5
          minute: 30
          hour: 300
          day: 3000
          policy: local
          fault_tolerant: true
  
  # 사용자 서비스 Health 전용 서비스
  - name: user-service-health
    url: http://user-service:3004/health
    routes:
      - name: user-health-route
        paths:
          - /api/health/users
    plugins:
      - name: cors

  # 리포트 서비스
  - name: report-service
    url: http://report-service:3005
    routes:
      - name: report-routes
        paths:
          - /api/v1/reports
        strip_path: false
    plugins:
      - name: cors
      # JWT 인증 적용
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
            - exp
          key_claim_name: kid
          maximum_expiration: 86400  # 24시간
      # 속도 제한 설정
      - name: rate-limiting
        config:
          second: 5
          minute: 30
          hour: 300
          day: 3000
          policy: local
          fault_tolerant: true
  
  # 리포트 서비스 Health 전용 서비스
  - name: report-service-health
    url: http://report-service:3005/health
    routes:
      - name: report-health-route
        paths:
          - /api/health/reports
    plugins:
      - name: cors

# Kong 소비자 및 JWT 구성
consumers:
  - username: haptitalk-app
    jwt_secrets:
      - algorithm: HS256
        key: "haptitalk-app-key"
        secret: "${JWT_ACCESS_SECRET}"
  
  - username: haptitalk-admin
    jwt_secrets:
      - algorithm: HS256
        key: "haptitalk-admin-key"
        secret: "${JWT_ACCESS_SECRET}"
    plugins:
      - name: rate-limiting
        config:
          second: 10
          minute: 100
          hour: 1000
          policy: local