version: '3.8'

services:
  # PostgreSQL - 관계형 데이터베이스 (사용자, 세션 데이터 등)
  postgres:
    image: postgres:14-alpine
    container_name: haptitalk-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME_NAME}:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - haptitalk_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB - 비정형 데이터베이스 (분석 결과, 대화 데이터 등)
  mongodb:
    image: mongo:5
    container_name: haptitalk-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ${MONGODB_VOLUME_NAME}:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - haptitalk_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis - 캐싱 및 메시지 브로커
  redis:
    image: redis:7-alpine
    container_name: haptitalk-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ${REDIS_VOLUME_NAME}:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - haptitalk_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong API 게이트웨이 (DB-less 모드)
  kong:
    image: kong:3.0
    container_name: haptitalk-kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./api-gateway/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "${KONG_PROXY_PORT}:8000"
      - "${KONG_HTTPS_PORT}:8443"
      - "${KONG_ADMIN_PORT}:8001"
      - "8444:8444"
    networks:
      - haptitalk_network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NGINX 리버스 프록시
  nginx:
    image: nginx:1.23-alpine
    container_name: haptitalk-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    networks:
      - haptitalk_network
    depends_on:
      - kong
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  haptitalk_network:
    driver: bridge

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME_NAME}
  mongodb_data:
    name: ${MONGODB_VOLUME_NAME}
  redis_data:
    name: ${REDIS_VOLUME_NAME}
  kong_data:
    name: ${KONG_VOLUME_NAME}