version: '3.8'

services:
  # Jaeger - 분산 트레이싱 시스템
  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: haptitalk-jaeger
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      # UI 포트
      - "${JAEGER_UI_PORT:-16686}:16686"
      # Jaeger 수집기 gRPC 포트
      - "${JAEGER_COLLECTOR_GRPC_PORT:-14250}:14250"
      # Jaeger 수집기 HTTP 포트
      - "${JAEGER_COLLECTOR_HTTP_PORT:-14268}:14268"
      # Jaeger 쿼리 서비스 포트
      - "${JAEGER_QUERY_PORT:-16685}:16685"
      # 에이전트 thrift compact 포트
      - "${JAEGER_AGENT_COMPACT_PORT:-6831}:6831/udp"
      # 에이전트 thrift binary 포트
      - "${JAEGER_AGENT_BINARY_PORT:-6832}:6832/udp"
      # Zipkin 호환성 포트
      - "${JAEGER_ZIPKIN_PORT:-9411}:9411"
      # OpenTelemetry 프로토콜 HTTP 수신 포트
      - "${JAEGER_OTLP_PORT:-4318}:4318"
      # OpenTelemetry 프로토콜 gRPC 수신 포트
      - "${JAEGER_OTLP_GRPC_PORT:-4317}:4317"
    volumes:
      - jaeger-data:/tmp
    networks:
      - jaeger_network
      - haptitalk_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 5

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    container_name: haptitalk-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${OTEL_COLLECTOR_PORT:-4317}:4317" # OTLP gRPC 수신
      - "${OTEL_COLLECTOR_HTTP_PORT:-4318}:4318" # OTLP HTTP 수신
      - "${OTEL_COLLECTOR_PROM_PORT:-8889}:8889" # Prometheus 지표 내보내기
      - "${OTEL_COLLECTOR_ZPAGES_PORT:-55679}:55679" # zPages
    depends_on:
      - jaeger
    networks:
      - jaeger_network
      - haptitalk_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jaeger-data:
    driver: local

networks:
  jaeger_network:
    driver: bridge
  haptitalk_network:
    external: true 