name: Secret Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # 매주 월요일 UTC 02:00에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  gitleaks:
    name: GitLeaks Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        continue-on-error: true
      
      - name: Upload GitLeaks scan results
        if: ${{ failure() || success() }}
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 7
      
      - name: Notify on findings
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL || 'security' }}
          SLACK_COLOR: 'danger'
          SLACK_TITLE: GitLeaks Secret Scan Alert
          SLACK_MESSAGE: 'GitLeaks scan detected potential secrets in repository. Please review scan results.'
          SLACK_FOOTER: 'Haptitalk Security'
