name: WatchOS CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/watch/**'
      - '.github/workflows/watch-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/watch/**'
      - '.github/workflows/watch-ci.yml'

jobs:
  build:
    name: Build WatchOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      
      - name: Build WatchOS App
        run: |
          cd frontend/watch/HaptiTalkWatch
          xcodebuild clean build -scheme "HaptiTalkWatch Watch App" -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" CODE_SIGNING_ALLOWED=NO
      
      - name: Run tests
        run: |
          cd frontend/watch/HaptiTalkWatch
          xcodebuild test -scheme "HaptiTalkWatch Watch App" -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" CODE_SIGNING_ALLOWED=NO || echo "No tests configured"
      
      - name: Archive WatchOS App
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          cd frontend/watch/HaptiTalkWatch
          xcodebuild archive -scheme "HaptiTalkWatch Watch App" -archivePath ./build/HaptiTalkWatch.xcarchive CODE_SIGNING_ALLOWED=NO
      
      - name: Upload build artifacts
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v3
        with:
          name: watchos-build
          path: frontend/watch/HaptiTalkWatch/build
          retention-days: 7
